name:                AnalisisDeSentimientos
version:             0.1.0.0
github:              "fcamposgonzlez/AnalisisDeSentimientos"
license:             BSD3
author:              "Fabi치n Campos Gonz치lez"
maintainer:          "fcamposgonzlez@gmail.com"
copyright:           "2019 Fabi치n Campos Gonz치lez"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            BIGDATA

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fcamposgonzlez/AnalisisDeSentimientos#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  AnalisisDeSentimientos-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AnalisisDeSentimientos

tests:
  AnalisisDeSentimientos-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AnalisisDeSentimientos
